language: r
cache: packages
pandoc_version: 1.19.2.1

before_install:
  - sudo apt-get -y install texlive-lang-portuguese

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
